package com.koreait.first.exception;

public class ExceptionTest3 {

	public static void main(String[] args) {
		try {
			div(10,2);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}
	public static void div(int n1, int n2) throws Exception {						//throws Exception 에러가 발생할 가능성이 있다고 표시를 해준다. (반드시 예외처리를 해줘야한다. try catch문)
		System.out.println(n1/n2);
	}

}
