package com.koreait.first.exception;

public class ExceptionTest {

	public static void main(String[] args) {
		int n1 = 10;
		int n2 = 2;
		
		try {
			System.out.println(n1 / n2);
			System.out.println("에러 안났음!");
		}
		catch (Exception e) {
			System.out.println("에러 발생!!");
		}
		System.out.println("안녕하세요!!");
		
	}

}
