package com.koreait.first.exception;

public class ExceptionTest2 {

	public static void main(String[] args) {
		
		
	}
	
	public static void div(int n1, int n2) {
		try {
			System.out.println(n1/n2);
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		finally {
			System.out.println("완료!");
		}
		System.out.println("--종료--");
	}

}
